# Generated by Django 4.1.5 on 2023-01-23 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='user_like')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='likes.like')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='posts.post', verbose_name='post_like')),
            ],
            options={
                'verbose_name': 'post like',
                'verbose_name_plural': 'Post likes',
            },
            bases=('likes.like',),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='likes.like')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='comments.comment', verbose_name='comment_like')),
            ],
            options={
                'verbose_name': 'comment like',
                'verbose_name_plural': 'Comment likes',
            },
            bases=('likes.like',),
        ),
    ]
